-- Table: public.products

-- DROP TABLE IF EXISTS public.products;

CREATE TABLE IF NOT EXISTS public.products
(
    product_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    product_name text COLLATE pg_catalog."default" NOT NULL,
    price numeric NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_product" PRIMARY KEY (product_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.products
    OWNER to postgres;

COMMENT ON TABLE public.products
    IS 'Список покупателей';

COMMENT ON COLUMN public.products.product_id
    IS 'Идентификатор продукта. Первичный ключ';

COMMENT ON COLUMN public.products.product_name
    IS 'Наименование продукта';

COMMENT ON COLUMN public.products.price
    IS 'Цена';

COMMENT ON COLUMN public.products.created_at
    IS 'Время создания записи в таблице';

INSERT INTO public.products(product_name, price )
VALUES                     ('Кофе'      , 300.50),
                           ('Сыр'       , 555.00),
                           ('Хлеб'      , 90.30 ),
                           ('Молоко'    , 155.00),
                           ('Шоколад'   , 200.25);

--
