-- Table: public.customers

-- DROP TABLE IF EXISTS public.customers;

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    second_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    birthdate date NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_customer" PRIMARY KEY (customer_id) 
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.customers
    OWNER to postgres;

COMMENT ON TABLE public.customers
    IS 'Список покупателей';

COMMENT ON COLUMN public.customers.customer_id 
    IS 'Уникальный идентификатор покупателя. Первичный ключ';

COMMENT ON COLUMN public.customers.first_name 
    IS 'Имя покупателя';

COMMENT ON COLUMN public.customers.second_name 
    IS 'Отчество покупателя';

COMMENT ON COLUMN public.customers.last_name
    IS 'Фамилия покупателя';

COMMENT ON COLUMN public.customers.birthdate
    IS 'День рождения покупателя';

COMMENT ON COLUMN public.customers.created_at
    IS 'Время создания записи в таблице';

INSERT INTO public.customers(first_name, second_name  , last_name  , birthdate)
VALUES                      ('Иван'    , 'Иванович'   , 'Иванов'   , '1986-01-01'),
                            ('Василий' , 'Васильевич' , 'Васильев' , '1961-02-02'),
                            ('Петр'    , 'Петрович'   , 'Петров'   , '1954-03-03'),
                            ('Сергей'  , 'Сергеевич'  , 'Сергеев'  , '1991-04-04'),
                            ('Алексей' , 'Алексеевич' , 'Алексеев' , '1973-05-05');

--
